# Generated by Django 3.1.7 on 2021-05-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('year', models.CharField(max_length=6, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(null=True)),
                ('pages', models.IntegerField(null=True)),
                ('languages', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
